server.name: kibana
server.host: "0"

server.cors: true
server.cors.origin: ["*"]
server.cors.additionalHeaders: ["kbn-xsrf", "kbn-version"]
server.cors.headers:
  [
    "accept",
    "authorization",
    "content-type",
    "if-none-match",
    "origin",
    "kbn-xsrf",
    "kbn-version",
  ]
server.cors.exposedHeaders:
  [
    "accept",
    "authorization",
    "content-type",
    "if-none-match",
    "origin",
    "kbn-xsrf",
    "kbn-version",
  ]
server.cors.additionalExposedHeaders: ["kbn-xsrf", "kbn-version"]

# server.ssl.enabled: true
# server.ssl.key: kibana.pem
# server.ssl.certificate: kibana-key.pem

elasticsearch.hosts:
  - ${ELASTICSEARCH_TARGET_INSTANCE_ONE}
  - ${ELASTICSEARCH_TARGET_INSTANCE_TWO}
elasticsearch.ssl.verificationMode: none
elasticsearch.username: ${KIBANA_USERNAME}
elasticsearch.password: ${KIBANA_PASSWORD}
opendistro_security.multitenancy.enabled: true

elasticsearch.requestHeadersWhitelist:
  [
    "securitytenant",
    "Authorization",
    "x-forwarded-for",
    "x-forwarded-by",
    "x-oauth-preferred_username",
    "x-oauth-realm",
  ]
opendistro_security.multitenancy.tenants.enable_private: false
opendistro_security.multitenancy.tenants.enable_global: false

opendistro_security.multitenancy.tenants.preferred: ["Private", "Global"]
opendistro_security.readonly_mode.roles: ["kibana_read_only"]

opendistro_security.auth.type: "proxy"

console.enabled: false

map.tilemap.url: https://maps.wikimedia.org/osm-intl/{z}/{x}/{y}.png
map.tilemap.options.maxZoom: 18
