_meta:
  type: "internalusers"
  config_version: 2

# password is: admin - for now
admin:
  reserved: true
  hash: "$2a$12$VcCDgh2NDk07JGN0rjGbM.Ad41qVR/YFJcgHp0UGns5JDymv..TOG"
  backend_roles:
    - "admin"
  description: "Admin user"

# Still using default password: logstash
logstash:
  hash: "$2y$12$SFNvhLHf7MPCpRCq00o/BuU8GMdcD.7BymhT80YHNISBHsfJwhTou"
  reserved: false
  backend_roles:
    - "logstash"
  description: "Logstash user"

# password is: kibanaserver - for now
kibanaserver:
  reserved: true
  hash: "$2a$12$4AcgAt3xwOWadA5s5blL6ev39OXDNhmOesEoo33eZtrq2N0YrU3H."
  description: "Kibana server user"

# Still using default password: kibanaro
kibanaro:
  reserved: false
  hash: "$2a$12$JJSXNfTowz7Uu5ttXfeYpeYE0arACvcwlPBStB1F.MI7f0U9Z4DGC"
  backend_roles:
    - "kibanauser"
    - "readall"
  attributes:
    #no dots allowed in attribute names
    attribute1: "value1"
    attribute2: "value2"
    attribute3: "value3"
  description: "Kibanaro user"

# Still using default password: readall
readall:
  hash: "$2a$12$ae4ycwzwvLtZxwZ82RmiEunBbIPiAmGZduBAjKN0TXdwQFtCwARz2"
  #password is: readall
  backend_roles:
    - "readall"
  description: "Readall user"

# Still using default password: snapshotrestore
snapshotrestore:
  hash: "$2y$12$DpwmetHKwgYnorbgdvORCenv4NAK8cPUg8AI6pxLCuWf/ALc0.v7W"
  reserved: false
  backend_roles:
    - "snapshotrestore"
  description: "Snapshotrestore user"
